### ISSUE TITLE
There is no template

### ISSUE THREAD

**Issue by Mogost** [mikekeda/django-debug-toolbar-line-profiling#1]
Hi @mikekeda. Thanks for your hard work.
Problem is here https://github.com/mikekeda/django-debug-toolbar-line-profiling/blob/b2b31f6124d7ce7bea1be3bac7bc991691e32397/MANIFEST.in#L3
Stack trace
```
Internal Server Error: /__debug__/render_panel/
Traceback (most recent call last):
  File ".../lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File ".../lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File ".../lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File ".../lib/python3.6/site-packages/debug_toolbar/decorators.py", line 15, in inner
    return view(request, *args, **kwargs)
  File ".../lib/python3.6/site-packages/debug_toolbar/views.py", line 21, in render_panel
    content = panel.content
  File ".../lib/python3.6/site-packages/debug_toolbar/panels/__init__.py", line 95, in content
    return render_to_string(self.template, self.get_stats())
  File ".../lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File ".../lib/python3.6/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: debug_toolbar_line_profiling/panels/profiling.html
```

I also do not quite understand why it was necessary to make a separate repository (not GH fork). Why not continue developing the library within your fork here https://github.com/mikekeda/django-debug-toolbar-line-profiler.
Use GH fork will have the advantage that your library can be found as a fork in Network of original library https://github.com/dmclain/django-debug-toolbar-line-profiler/network.

It also seems to me wiser to change only the name on pypi and not change the internal structure, this will give a smooth transition from the old version to the new one.
My suggestion is to remove this repository and continue working [here](https://github.com/mikekeda/django-debug-toolbar-line-profiler).

**Comment by mikekeda** [comment]
fixed in version 0.7.1
I will delete this repository later

**Comment by Mogost** [comment]
Thank! I will test the new version in the coming days.

**Comment by Mogost** [comment]
@mikekeda Please do not forget to enable issues option for https://github.com/mikekeda/django-debug-toolbar-line-profiler
